test:
  adapter: async

development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: nsb-api_development

production:
  adapter: redis
  url: redis://h:p2ea001dc399a85146bbb91313833fb3fb93df4968f86ace771c5dfeaccb80409@ec2-52-3-6-123.compute-1.amazonaws.com:29009
  channel_prefix: nsb-api_production
