test:
  adapter: async

development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: nsb-api_development

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: nsb-api_production
